// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: alerts.proto

package alerts

import (
	common "github.com/afikmenashe/alerting-platform/pkg/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AlertNew represents a new alert event (alerts.new topic)
type AlertNew struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`                                                            // UUID v4
	SchemaVersion int32                  `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`                                         // Schema version (currently 1)
	EventTs       int64                  `protobuf:"varint,3,opt,name=event_ts,json=eventTs,proto3" json:"event_ts,omitempty"`                                                           // Unix timestamp (seconds)
	Severity      common.Severity        `protobuf:"varint,4,opt,name=severity,proto3,enum=alerting.common.Severity" json:"severity,omitempty"`                                          // Alert severity
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`                                                                             // Source system
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`                                                                                 // Alert name/type
	Context       map[string]string      `protobuf:"bytes,7,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional context metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertNew) Reset() {
	*x = AlertNew{}
	mi := &file_alerts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertNew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertNew) ProtoMessage() {}

func (x *AlertNew) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertNew.ProtoReflect.Descriptor instead.
func (*AlertNew) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{0}
}

func (x *AlertNew) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *AlertNew) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *AlertNew) GetEventTs() int64 {
	if x != nil {
		return x.EventTs
	}
	return 0
}

func (x *AlertNew) GetSeverity() common.Severity {
	if x != nil {
		return x.Severity
	}
	return common.Severity(0)
}

func (x *AlertNew) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AlertNew) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlertNew) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// AlertMatched represents a matched alert (alerts.matched topic)
type AlertMatched struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	SchemaVersion int32                  `protobuf:"varint,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventTs       int64                  `protobuf:"varint,3,opt,name=event_ts,json=eventTs,proto3" json:"event_ts,omitempty"`
	Severity      common.Severity        `protobuf:"varint,4,opt,name=severity,proto3,enum=alerting.common.Severity" json:"severity,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Context       map[string]string      `protobuf:"bytes,7,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ClientId      string                 `protobuf:"bytes,8,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // Client this alert matched for
	RuleIds       []string               `protobuf:"bytes,9,rep,name=rule_ids,json=ruleIds,proto3" json:"rule_ids,omitempty"`    // Rule IDs that matched
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertMatched) Reset() {
	*x = AlertMatched{}
	mi := &file_alerts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertMatched) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertMatched) ProtoMessage() {}

func (x *AlertMatched) ProtoReflect() protoreflect.Message {
	mi := &file_alerts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertMatched.ProtoReflect.Descriptor instead.
func (*AlertMatched) Descriptor() ([]byte, []int) {
	return file_alerts_proto_rawDescGZIP(), []int{1}
}

func (x *AlertMatched) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *AlertMatched) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *AlertMatched) GetEventTs() int64 {
	if x != nil {
		return x.EventTs
	}
	return 0
}

func (x *AlertMatched) GetSeverity() common.Severity {
	if x != nil {
		return x.Severity
	}
	return common.Severity(0)
}

func (x *AlertMatched) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AlertMatched) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlertMatched) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *AlertMatched) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AlertMatched) GetRuleIds() []string {
	if x != nil {
		return x.RuleIds
	}
	return nil
}

var File_alerts_proto protoreflect.FileDescriptor

const file_alerts_proto_rawDesc = "" +
	"\n" +
	"\falerts.proto\x12\x0falerting.alerts\x1a\fcommon.proto\"\xc8\x02\n" +
	"\bAlertNew\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\x05R\rschemaVersion\x12\x19\n" +
	"\bevent_ts\x18\x03 \x01(\x03R\aeventTs\x125\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x19.alerting.common.SeverityR\bseverity\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12@\n" +
	"\acontext\x18\a \x03(\v2&.alerting.alerts.AlertNew.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x03\n" +
	"\fAlertMatched\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\x05R\rschemaVersion\x12\x19\n" +
	"\bevent_ts\x18\x03 \x01(\x03R\aeventTs\x125\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x19.alerting.common.SeverityR\bseverity\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12D\n" +
	"\acontext\x18\a \x03(\v2*.alerting.alerts.AlertMatched.ContextEntryR\acontext\x12\x1b\n" +
	"\tclient_id\x18\b \x01(\tR\bclientId\x12\x19\n" +
	"\brule_ids\x18\t \x03(\tR\aruleIds\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B;Z9github.com/afikmenashe/alerting-platform/pkg/proto/alertsb\x06proto3"

var (
	file_alerts_proto_rawDescOnce sync.Once
	file_alerts_proto_rawDescData []byte
)

func file_alerts_proto_rawDescGZIP() []byte {
	file_alerts_proto_rawDescOnce.Do(func() {
		file_alerts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alerts_proto_rawDesc), len(file_alerts_proto_rawDesc)))
	})
	return file_alerts_proto_rawDescData
}

var file_alerts_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_alerts_proto_goTypes = []any{
	(*AlertNew)(nil),     // 0: alerting.alerts.AlertNew
	(*AlertMatched)(nil), // 1: alerting.alerts.AlertMatched
	nil,                  // 2: alerting.alerts.AlertNew.ContextEntry
	nil,                  // 3: alerting.alerts.AlertMatched.ContextEntry
	(common.Severity)(0), // 4: alerting.common.Severity
}
var file_alerts_proto_depIdxs = []int32{
	4, // 0: alerting.alerts.AlertNew.severity:type_name -> alerting.common.Severity
	2, // 1: alerting.alerts.AlertNew.context:type_name -> alerting.alerts.AlertNew.ContextEntry
	4, // 2: alerting.alerts.AlertMatched.severity:type_name -> alerting.common.Severity
	3, // 3: alerting.alerts.AlertMatched.context:type_name -> alerting.alerts.AlertMatched.ContextEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_alerts_proto_init() }
func file_alerts_proto_init() {
	if File_alerts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alerts_proto_rawDesc), len(file_alerts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alerts_proto_goTypes,
		DependencyIndexes: file_alerts_proto_depIdxs,
		MessageInfos:      file_alerts_proto_msgTypes,
	}.Build()
	File_alerts_proto = out.File
	file_alerts_proto_goTypes = nil
	file_alerts_proto_depIdxs = nil
}
